= DB Internal Handler

The DB Internal handler will store all the Event Notifications produced from the
Mule ESB flows in a configurable database.
You have to copy your JDBC .jar driver to the {MULE_HOME}/plugins/mule-agent-plugin/lib,
so the mule agent can load it to the classpath.

=== Configurable Fields


|===
|Field|Data Type|Description|Type|Default Value

|driver
|String
|Represents the JDBC driver to use to communicate with the database server.
|Required
|

|jdbcUrl
|String
|Represents the JDBC url to the database server.
|Required
|

|user
|String
|The username to connect to the database server.
|Optional
|blank

|pass
|String
|The password to connect to the database server.
|Optional
|blank

|table
|String
|Represents the name of the table in which the agent will store the events.
|Optional
|MULE_EVENTS

|===

=== Proposed Table Schema to Store the Events

[source,sql]
....
CREATE TABLE MULE_EVENTS (
	Action varchar(500) NULL,
	Application varchar(500) NULL,
	MuleMessage varchar(500) NULL,
	MuleMessageId varchar(500) NULL,
	NotificationType varchar(500) NULL,
	Path varchar(500) NULL,
	ResourceIdentifier varchar(500) NULL,
	Timestamp int NULL,
	Source varchar(500) NULL
)
....

=== Configuration Example for MySQL

[source,yaml]
.DB Internal Handler Configuration
....
---
  mule.agent.tracking.handler.database:
    driver: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.61.128/mule
    user: root
    pass: test
    table: mule
....